image: Visual Studio 2017
clone_folder: c:\projects\BlendNet

environment:
    WORKSPACE: C:\projects
    matrix:
    - platform: Win64
      COMPILER: vs
      MSVC_SETUP_ARG: x64
      PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.3"
      PYTHON_ARCH: "64"
      MINICONDA: "C:\\Miniconda36-x64"

install:
  # Use Miniconda to accelerate the build (max time for CI is 60 minutes!)
  - "SET PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - "python -m pip install -U pip"
  - "python --version"
  - "pip --version"
  - "SET PROFILE=C:\\Users\\appveyor\\Documents\\WindowsPowerShell\\Microsoft.PowerShell_profile.ps1"

  - git submodule -q update --init --recursive

before_build:
  - cd C:\projects\BlendNet

build_script:
  - ps: .\install.ps1 -y


